import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <main className="w-full h-screen flex flex-col items-center justify-center bg-[#101E32]">
          <div className="w-[450px] h-[800px] bg-white rounded-lg shadow-lg flex flex-col ">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
